[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "poppler_utils"]

[deploy]
startCommand = "gunicorn app:app --workers 1 --threads 4 --timeout 300 --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
